                                                            /*secret*/
INSERT INTO USERSTEST VALUES (1, TRUE,  'MIF@MIF.MIF','MIF',   'q4r5MF5qe5RPtcCyFb9EtA==',   '380994546082');
                                                              /*smith*/
INSERT INTO USERSTEST VALUES (2, FALSE, 'John@John.John', 'John', 'Pc0F0ypOPpdtQIeMq3HULQ==',  '380994546182');



INSERT  INTO CATEGORIES VALUES (1, 'SmartPhones');

INSERT  INTO CATEGORIES VALUES (2, 'Home appliances');

INSERT  INTO CATEGORIES VALUES (3, 'Laptop');



INSERT  INTO PRODUCTS VALUES (1, 'Iphone5', 15500);

INSERT  INTO PRODUCTS VALUES (2, 'SAMSUNG Galaxy3', 14000);

INSERT  INTO PRODUCTS VALUES (3, 'Sony xperia z1', 12000);

INSERT  INTO PRODUCTS VALUES (4, 'Refrigerator LG', 12300);

INSERT  INTO PRODUCTS VALUES (5, 'Washing machine INDESIT', 9600);

INSERT  INTO PRODUCTS VALUES (6, 'Dishwasher BOSCH', 10300);

INSERT  INTO PRODUCTS VALUES (7, 'Lenovo Flex 2', 19900);

INSERT  INTO PRODUCTS VALUES (8, 'HP Zbook', 30000);

INSERT  INTO PRODUCTS VALUES (9, 'Acer Aspire', 21000);


INSERT  INTO CATEGORY_PRODUCT VALUES (1, 1);

INSERT  INTO CATEGORY_PRODUCT VALUES (1, 2);

INSERT  INTO CATEGORY_PRODUCT VALUES (1, 3);

INSERT  INTO CATEGORY_PRODUCT VALUES (2, 4);

INSERT  INTO CATEGORY_PRODUCT VALUES (2, 5);

INSERT  INTO CATEGORY_PRODUCT VALUES (2, 6);

INSERT  INTO CATEGORY_PRODUCT VALUES (3, 7);

INSERT  INTO CATEGORY_PRODUCT VALUES (3, 8);

INSERT  INTO CATEGORY_PRODUCT VALUES (3, 9);
